### Crear usuario
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "josuabejon@gmail.com",
    "password": "1234567890"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "josu.abejon@gmail.com",
    "password": "Password1*"
}

### Get Summary
GET http://localhost:3000/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1ODEwNiwiZXhwIjoxNzM4MjYxMTA2fQ.hnenaVjBe7QVimZW6TQkr_-UCvpOT7S6IqtBMdqA64k
UserId: 6793f2453930e0c92d1c763f

### Create Bill
POST http://localhost:3000/bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1NTA2MSwiZXhwIjoxNzM4MjU4MDYxfQ.EScw9aYITen1rD8pKMA37P1XhRxCSD116dwAYf7NTs8
UserId: 6793f2453930e0c92d1c763f

{
    "bill": {
        "billType": "leisure",
        "billText": "prueba2",
        "amount": 111,
        "date": "9/2/2025"
    }
}

### Update Bill
PATCH  http://localhost:3000/bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1NTg0OSwiZXhwIjoxNzM4MjU4ODQ5fQ.Weaiw7FjsdvbWCRj3ppRU8dHF_TPSfyhKghpZnQ0xvk
UserId: 6793f2453930e0c92d1c763f

{
    "bill": {
        "amount": 2343,
        "billText": "prueba3",
        "_id": "679bb407a9b5baf07d89b429",
        "date": "19/1/2025",
        "billType": "leisure"
    }
}

### Delete Bill
DELETE   http://localhost:3000/bill?id=679bb407a9b5baf07d89b429
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1NTg0OSwiZXhwIjoxNzM4MjU4ODQ5fQ.Weaiw7FjsdvbWCRj3ppRU8dHF_TPSfyhKghpZnQ0xvk
UserId: 6793f2453930e0c92d1c763f

### Get Salary
GET     http://localhost:3000/salary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1MTQ1OCwiZXhwIjoxNzM4MjU0NDU4fQ.IOtlrXFXAxw6bm76jzQ-6qSYMvTRUbciGkyzMI2u4gA
UserId: 6793f2453930e0c92d1c763f

### Set Salary
POST    http://localhost:3000/salary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODI1MTQ1OCwiZXhwIjoxNzM4MjU0NDU4fQ.IOtlrXFXAxw6bm76jzQ-6qSYMvTRUbciGkyzMI2u4gA
UserId: 6793f2453930e0c92d1c763f

{
    "salary": 2000,
    "month": "Febrero"
}