### Crear usuario
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "josuabejon@gmail.com",
    "password": "1234567890"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "josu.abejon@gmail.com",
    "password": "Password1*"
}

### Get Summary
GET http://localhost:3000/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE2NDQwOSwiZXhwIjoxNzM4MTY3NDA5fQ.prM47Br3ZYdz1G7cgju6dhpf51oc54jI0QOXvWlG8Zs
UserId: 6793f2453930e0c92d1c763f

### Create Bill
POST http://localhost:3000/bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE1Mzc3NSwiZXhwIjoxNzM4MTU2Nzc1fQ.3iYYw39pizU04jAPHrqs1UdXSqu22lSd5Ie3IjJJ0rs
UserId: 6793f2453930e0c92d1c763f

{
    "bill": {
        "billType": "leisure",
        "billText": "Patch",
        "amount": 111,
        "date": "29/1/2025"
    }
}

### Update Bill
PATCH  http://localhost:3000/bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE1NTA0NSwiZXhwIjoxNzM4MTU4MDQ1fQ.qfPiJu-94h4RfxVUHR9O_ojm7kGwvDP-vWr6c3jAZWU
UserId: 6793f2453930e0c92d1c763f

{
    "amount": 103,
    "id": "679a222c7bb86cd5c522d195"
}

### Delete Bill
DELETE   http://localhost:3000/bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE2NDQwOSwiZXhwIjoxNzM4MTY3NDA5fQ.prM47Br3ZYdz1G7cgju6dhpf51oc54jI0QOXvWlG8Zs
UserId: 6793f2453930e0c92d1c763f

{
    "id": "679a329b00bdca5db9f0495a"
}

### Get Salary
GET     http://localhost:3000/salary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE1NzQ5MSwiZXhwIjoxNzM4MTYwNDkxfQ.XrsMPr2Fx7KaiK91vftYsMDIXeas-Eodc1b7_ByVu3g
UserId: 6793f2453930e0c92d1c763f

### Set Salary
POST    http://localhost:3000/salary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc3UuYWJlam9uQGdtYWlsLmNvbSIsImlhdCI6MTczODE1NzQ5MSwiZXhwIjoxNzM4MTYwNDkxfQ.XrsMPr2Fx7KaiK91vftYsMDIXeas-Eodc1b7_ByVu3g
UserId: 6793f2453930e0c92d1c763f

{
    "salary": 1501
}