### Añadir un nuevo bill
POST http://localhost:3000/bill
Content-Type: application/json

{
    "fixedCost": 100,
    "leisure": 20,
    "saving": 30
}
### Crear usuario
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "josuabejon@gmail.com",
    "password": "1234567890"
}

### Login
POST https://five0-30-20-express.onrender.com/login
Content-Type: application/json

{
    "email": "josuabejon@gmail.com",
    "password": "Password1*"
}

### Get Summary
GET http://localhost:3000/summary